[general]
import = [
    "~/.config/alacritty/solarized_osaka-mod.toml",
    "~/.config/alacritty/keybindings.toml",
    "~/.config/alacritty/platform-specific.toml"
]

[window]
dimensions = { columns = 120, lines = 32 }
padding = { x = 1, y = 1 }
option_as_alt = "Both"

[font]
# JetBrainsMono Nerd Font
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12
offset = { x = 0, y = 2 }
# Monaco Nerd Font Mono
#normal = { family = "Monaco Nerd Font Mono", style = "Regular" }
#size = 12
#offset = { x = 0, y = 1 }

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
